import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Navbar} from "@/components/navbar"
import { GoogleAnalytics } from '@next/third-parties/google'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your OTP 2FA Safebox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      <main>{children}</main>
      </body>
      <GoogleAnalytics gaId="G-RWD6QBZ35S" />
    </html>
  );
}
